// NYC subway stations: [gtfsStopId, name, borough, routes, northLabel, southLabel].
// Generated from the MTA Subway Stations dataset (data.ny.gov 39hk-dx4f, July 2026)
// by scripts/gen-mta-stations.mjs - regenerate rather than hand-editing.
// Bare "Inbound"/"Outbound" dataset labels are replaced with route terminal
// names at generation time; "Last Stop" directions are skipped at format time.
// Borough: M=Manhattan, Bk=Brooklyn, Q=Queens, Bx=Bronx, SI=Staten Island.
export type MtaStation = [string, string, string, string, string, string];

export const MTA_STATIONS: MtaStation[] = [
  ["101","Van Cortlandt Park-242 St","Bx","1","Last Stop","Manhattan"],
  ["103","238 St","Bx","1","Van Cortlandt","Manhattan"],
  ["104","231 St","Bx","1","Van Cortlandt","Manhattan"],
  ["106","Marble Hill-225 St","M","1","The Bronx","Downtown"],
  ["107","215 St","M","1","The Bronx","Downtown"],
  ["108","207 St","M","1","The Bronx","Downtown"],
  ["109","Dyckman St","M","1","The Bronx","Downtown"],
  ["110","191 St","M","1","The Bronx","Downtown"],
  ["111","181 St","M","1","The Bronx","Downtown"],
  ["112","168 St-Washington Hts","M","1","Uptown","Downtown"],
  ["113","157 St","M","1","Uptown","Downtown"],
  ["114","145 St","M","1","Uptown","Downtown"],
  ["115","137 St-City College","M","1","Uptown","Downtown"],
  ["116","125 St","M","1","Uptown","Downtown"],
  ["117","116 St-Columbia University","M","1","Uptown","Downtown"],
  ["118","Cathedral Pkwy (110 St)","M","1","Uptown","Downtown"],
  ["119","103 St","M","1","Uptown","Downtown"],
  ["120","96 St","M","1 2 3","Uptown","Downtown"],
  ["121","86 St","M","1","Uptown","Downtown"],
  ["122","79 St","M","1","Uptown","Downtown"],
  ["123","72 St","M","1 2 3","Uptown","Downtown"],
  ["124","66 St-Lincoln Center","M","1","Uptown","Downtown"],
  ["125","59 St-Columbus Circle","M","1","Uptown","Downtown"],
  ["126","50 St","M","1","Uptown","Downtown"],
  ["127","Times Sq-42 St","M","1 2 3","Uptown","Downtown"],
  ["128","34 St-Penn Station","M","1 2 3","Uptown","Downtown"],
  ["129","28 St","M","1","Uptown","Downtown"],
  ["130","23 St","M","1","Uptown","Downtown"],
  ["131","18 St","M","1","Uptown","Downtown"],
  ["132","14 St","M","1 2 3","Uptown","Downtown"],
  ["133","Christopher St-Stonewall","M","1","Uptown","Downtown"],
  ["134","Houston St","M","1","Uptown","Downtown"],
  ["135","Canal St","M","1","Uptown","Downtown"],
  ["136","Franklin St","M","1","Uptown","Downtown"],
  ["137","Chambers St","M","1 2 3","Uptown","Downtown"],
  ["138","WTC Cortlandt","M","1","Uptown","Downtown"],
  ["139","Rector St","M","1","Uptown","Downtown"],
  ["142","South Ferry","M","1","Uptown","Last Stop"],
  ["201","Wakefield-241 St","Bx","2","Last Stop","Manhattan"],
  ["204","Nereid Av","Bx","2 5","Northbound","Manhattan"],
  ["205","233 St","Bx","2 5","Northbound","Manhattan"],
  ["206","225 St","Bx","2 5","Northbound","Manhattan"],
  ["207","219 St","Bx","2 5","Northbound","Manhattan"],
  ["208","Gun Hill Rd","Bx","2 5","Northbound","Manhattan"],
  ["209","Burke Av","Bx","2 5","Northbound","Manhattan"],
  ["210","Allerton Av","Bx","2 5","Northbound","Manhattan"],
  ["211","Pelham Pkwy","Bx","2 5","Northbound","Manhattan"],
  ["212","Bronx Park East","Bx","2 5","Northbound","Manhattan"],
  ["213","E 180 St","Bx","2 5","Northbound","Manhattan"],
  ["214","West Farms Sq-E Tremont Av","Bx","2 5","Northbound","Manhattan"],
  ["215","174 St","Bx","2 5","Northbound","Manhattan"],
  ["216","Freeman St","Bx","2 5","Northbound","Manhattan"],
  ["217","Simpson St","Bx","2 5","Northbound","Manhattan"],
  ["218","Intervale Av","Bx","2 5","Northbound","Manhattan"],
  ["219","Prospect Av","Bx","2 5","Northbound","Manhattan"],
  ["220","Jackson Av","Bx","2 5","Northbound","Manhattan"],
  ["221","3 Av-149 St","Bx","2 5","Northbound","Manhattan"],
  ["222","149 St-Grand Concourse","Bx","2 5","Northbound","Manhattan"],
  ["224","135 St","M","2 3","Uptown","Downtown"],
  ["225","125 St","M","2 3","Uptown","Downtown"],
  ["226","116 St","M","2 3","Uptown","Downtown"],
  ["227","110 St-Malcolm X Plaza","M","2 3","Uptown","Downtown"],
  ["228","Park Place","M","2 3","Uptown","Brooklyn"],
  ["229","Fulton St","M","2 3","Uptown","Brooklyn"],
  ["230","Wall St","M","2 3","Uptown","Brooklyn"],
  ["231","Clark St","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["232","Borough Hall","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["233","Hoyt St","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["234","Nevins St","Bk","2 3 4 5","Manhattan","Flatbush Av/New Lots Av/Utica Av"],
  ["235","Atlantic Av-Barclays Ctr","Bk","2 3 4 5","Manhattan","Flatbush Av/New Lots Av/Utica Av"],
  ["236","Bergen St","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["237","Grand Army Plaza","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["238","Eastern Pkwy-Brooklyn Museum","Bk","2 3","Manhattan","Flatbush Av/New Lots Av"],
  ["239","Franklin Av-Medgar Evers College","Bk","2 3 4 5","Manhattan","Flatbush Av/New Lots Av/Utica Av"],
  ["241","President St-Medgar Evers College","Bk","2 5","Manhattan","Flatbush"],
  ["242","Sterling St","Bk","2 5","Manhattan","Flatbush"],
  ["243","Winthrop St","Bk","2 5","Manhattan","Flatbush"],
  ["244","Church Av","Bk","2 5","Manhattan","Flatbush"],
  ["245","Beverly Rd","Bk","2 5","Manhattan","Flatbush"],
  ["246","Newkirk Av-Little Haiti","Bk","2 5","Manhattan","Flatbush"],
  ["247","Flatbush Av-Brooklyn College","Bk","2 5","Manhattan","Last Stop"],
  ["248","Nostrand Av","Bk","3","Manhattan","New Lots Av"],
  ["249","Kingston Av","Bk","3","Manhattan","New Lots Av"],
  ["250","Crown Hts-Utica Av","Bk","3 4","Manhattan","New Lots Av/Utica Av"],
  ["251","Sutter Av-Rutland Rd","Bk","3","Manhattan","New Lots"],
  ["252","Saratoga Av","Bk","3","Manhattan","New Lots"],
  ["253","Rockaway Av","Bk","3","Manhattan","New Lots"],
  ["254","Junius St","Bk","3","Manhattan","New Lots"],
  ["255","Pennsylvania Av","Bk","3","Manhattan","New Lots"],
  ["256","Van Siclen Av","Bk","3","Manhattan","New Lots"],
  ["257","New Lots Av","Bk","3","Manhattan","Last Stop"],
  ["301","Harlem-148 St","M","3","Last Stop","Downtown"],
  ["302","145 St","M","3","Harlem","Downtown"],
  ["401","Woodlawn","Bx","4","Last Stop","Manhattan"],
  ["402","Mosholu Pkwy","Bx","4","Woodlawn","Manhattan"],
  ["405","Bedford Park Blvd-Lehman College","Bx","4","Northbound","Manhattan"],
  ["406","Kingsbridge Rd","Bx","4","Northbound","Manhattan"],
  ["407","Fordham Rd","Bx","4","Northbound","Manhattan"],
  ["408","183 St","Bx","4","Northbound","Manhattan"],
  ["409","Burnside Av","Bx","4","Northbound","Manhattan"],
  ["410","176 St","Bx","4","Northbound","Manhattan"],
  ["411","Mt Eden Av","Bx","4","Northbound","Manhattan"],
  ["412","170 St","Bx","4","Northbound","Manhattan"],
  ["413","167 St","Bx","4","Northbound","Manhattan"],
  ["414","161 St-Yankee Stadium","Bx","4","Northbound","Manhattan"],
  ["415","149 St-Grand Concourse","Bx","4","Northbound","Manhattan"],
  ["416","138 St-Grand Concourse","Bx","4 5","Northbound","Manhattan"],
  ["418","Fulton St","M","4 5","Uptown","Downtown"],
  ["419","Wall St","M","4 5","Uptown","Downtown"],
  ["420","Bowling Green","M","4 5","Uptown","Downtown"],
  ["423","Borough Hall","Bk","4 5","Manhattan","Utica Av/Flatbush Av"],
  ["501","Eastchester-Dyre Av","Bx","5","Last Stop","Manhattan"],
  ["502","Baychester Av","Bx","5","Eastchester","Manhattan"],
  ["503","Gun Hill Rd","Bx","5","Eastchester","Manhattan"],
  ["504","Pelham Pkwy","Bx","5","Eastchester","Manhattan"],
  ["505","Morris Park","Bx","5","Eastchester","Manhattan"],
  ["601","Pelham Bay Park","Bx","6","Last Stop","Manhattan"],
  ["602","Buhre Av","Bx","6","Pelham Bay","Manhattan"],
  ["603","Middletown Rd","Bx","6","Pelham Bay","Manhattan"],
  ["604","Westchester Sq-E Tremont Av","Bx","6","Pelham Bay","Manhattan"],
  ["606","Zerega Av","Bx","6","Pelham Bay","Manhattan"],
  ["607","Castle Hill Av","Bx","6","Pelham Bay","Manhattan"],
  ["608","Parkchester","Bx","6","Northbound","Manhattan"],
  ["609","St Lawrence Av","Bx","6","Northbound","Manhattan"],
  ["610","Morrison Av-Soundview","Bx","6","Northbound","Manhattan"],
  ["611","Elder Av","Bx","6","Northbound","Manhattan"],
  ["612","Whitlock Av","Bx","6","Northbound","Manhattan"],
  ["613","Hunts Point Av","Bx","6","Northbound","Manhattan"],
  ["614","Longwood Av","Bx","6","Northbound","Manhattan"],
  ["615","E 149 St","Bx","6","Northbound","Manhattan"],
  ["616","E 143 St-St Mary's St","Bx","6","Northbound","Manhattan"],
  ["617","Cypress Av","Bx","6","Northbound","Manhattan"],
  ["618","Brook Av","Bx","6","Northbound","Manhattan"],
  ["619","3 Av-138 St","Bx","6","Northbound","Manhattan"],
  ["621","125 St","M","4 5 6","The Bronx","Downtown"],
  ["622","116 St","M","6","The Bronx","Downtown"],
  ["623","110 St","M","6","The Bronx","Downtown"],
  ["624","103 St","M","6","The Bronx","Downtown"],
  ["625","96 St","M","6","The Bronx","Downtown"],
  ["626","86 St","M","4 5 6","Uptown","Downtown"],
  ["627","77 St","M","6","Uptown","Downtown"],
  ["628","68 St-Hunter College","M","6","Uptown","Downtown"],
  ["629","59 St","M","4 5 6","Uptown","Downtown"],
  ["630","51 St","M","6","Uptown","Downtown"],
  ["631","Grand Central-42 St","M","4 5 6","Uptown","Downtown"],
  ["632","33 St","M","6","Uptown","Downtown"],
  ["633","28 St","M","6","Uptown","Downtown"],
  ["634","23 St-Baruch College","M","6","Uptown","Downtown"],
  ["635","14 St-Union Sq","M","4 5 6","Uptown","Downtown"],
  ["636","Astor Pl","M","6","Uptown","Downtown"],
  ["637","Bleecker St","M","6","Uptown","Downtown"],
  ["638","Spring St","M","6","Uptown","Downtown"],
  ["639","Canal St","M","6","Uptown","Downtown"],
  ["640","Brooklyn Bridge-City Hall","M","4 5 6","Uptown","Downtown"],
  ["701","Flushing-Main St","Q","7","Last Stop","Manhattan"],
  ["702","Mets-Willets Point","Q","7","Flushing-Main St","Manhattan"],
  ["705","111 St","Q","7","Flushing-Main St","Manhattan"],
  ["706","103 St-Corona Plaza","Q","7","Flushing-Main St","Manhattan"],
  ["707","Junction Blvd","Q","7","Flushing-Main St","Manhattan"],
  ["708","90 St-Elmhurst Av","Q","7","Flushing-Main St","Manhattan"],
  ["709","82 St-Jackson Hts","Q","7","Flushing-Main St","Manhattan"],
  ["710","74 St-Broadway","Q","7","Flushing-Main St","Manhattan"],
  ["711","69 St","Q","7","Flushing-Main St","Manhattan"],
  ["712","61 St-Woodside","Q","7","Flushing-Main St","Manhattan"],
  ["713","52 St","Q","7","Flushing-Main St","Manhattan"],
  ["714","46 St-Bliss St","Q","7","Flushing-Main St","Manhattan"],
  ["715","40 St-Lowery St","Q","7","Flushing-Main St","Manhattan"],
  ["716","33 St-Rawson St","Q","7","Flushing-Main St","Manhattan"],
  ["718","Queensboro Plaza","Q","7","Flushing-Main St","Manhattan"],
  ["719","Court Sq","Q","7","Flushing-Main St","Manhattan"],
  ["720","Hunters Point Av","Q","7","Flushing-Main St","Manhattan"],
  ["721","Vernon Blvd-Jackson Av","Q","7","Flushing-Main St","Manhattan"],
  ["723","Grand Central-42 St","M","7","Queens","Hudson Yards"],
  ["724","5 Av","M","7","Queens","Hudson Yards"],
  ["725","Times Sq-42 St","M","7","Queens","Hudson Yards"],
  ["726","34 St-Hudson Yards","M","7","Last Stop","Queens"],
  ["901","Grand Central-42 St","M","S","Times Square","Last Stop"],
  ["902","Times Sq-42 St","M","S","Last Stop","Grand Central"],
  ["A02","Inwood-207 St","M","A","Last Stop","Downtown"],
  ["A03","Dyckman St","M","A","Uptown","Downtown"],
  ["A05","190 St","M","A","Uptown","Downtown"],
  ["A06","181 St","M","A","Uptown","Downtown"],
  ["A07","175 St","M","A","Uptown","Downtown"],
  ["A09","168 St","M","A C","Uptown","Downtown"],
  ["A10","163 St-Amsterdam Av","M","C","Uptown","Downtown"],
  ["A11","155 St","M","C","Uptown","Downtown"],
  ["A12","145 St","M","A C","Uptown","Downtown"],
  ["A14","135 St","M","C B","Uptown","Downtown"],
  ["A15","125 St","M","A C B D","Uptown","Downtown"],
  ["A16","116 St","M","C B","Uptown","Downtown"],
  ["A17","Cathedral Pkwy (110 St)","M","C B","Uptown","Downtown"],
  ["A18","103 St","M","C B","Uptown","Downtown"],
  ["A19","96 St","M","C B","Uptown","Downtown"],
  ["A20","86 St","M","C B","Uptown","Downtown"],
  ["A21","81 St-Museum of Natural History","M","C B","Uptown","Downtown"],
  ["A22","72 St","M","C B","Uptown","Downtown"],
  ["A24","59 St-Columbus Circle","M","A C B D","Uptown","Downtown"],
  ["A25","50 St","M","C E","Uptown","Downtown"],
  ["A27","42 St-Port Authority Bus Terminal","M","A C E","Uptown","Downtown"],
  ["A28","34 St-Penn Station","M","A C E","Uptown","Downtown"],
  ["A30","23 St","M","C E","Uptown","Downtown"],
  ["A31","14 St","M","A C E","Uptown","Downtown"],
  ["A32","W 4 St-Wash Sq","M","A C E","Uptown","Downtown"],
  ["A33","Spring St","M","C E","Uptown","Downtown"],
  ["A34","Canal St","M","A C E","Uptown","Downtown"],
  ["A36","Chambers St","M","A C","Uptown","Brooklyn"],
  ["A38","Fulton St","M","A C","Uptown","Brooklyn"],
  ["A40","High St","Bk","A C","Manhattan","Far Rockaway/Ozone Park/Euclid Av"],
  ["A41","Jay St-MetroTech","Bk","A C F","Manhattan","Far Rockaway/Ozone Park/Euclid Av/Coney Island"],
  ["A42","Hoyt-Schermerhorn Sts","Bk","A C G","Westbound","Queens"],
  ["A43","Lafayette Av","Bk","C","Manhattan","Euclid Av"],
  ["A44","Clinton-Washington Avs","Bk","C","Manhattan","Euclid Av"],
  ["A45","Franklin Av","Bk","C","Manhattan","Euclid Av"],
  ["A46","Nostrand Av","Bk","A C","Manhattan","Far Rockaway/Ozone Park/Euclid Av"],
  ["A47","Kingston-Throop Avs","Bk","C","Manhattan","Euclid Av"],
  ["A48","Utica Av","Bk","A C","Manhattan","Far Rockaway/Ozone Park/Euclid Av"],
  ["A49","Ralph Av","Bk","C","Manhattan","Euclid Av"],
  ["A50","Rockaway Av","Bk","C","Manhattan","Euclid Av"],
  ["A51","Broadway Junction","Bk","A C","Manhattan","Far Rockaway/Ozone Park/Euclid Av"],
  ["A52","Liberty Av","Bk","C","Manhattan","Euclid Av"],
  ["A53","Van Siclen Av","Bk","C","Manhattan","Euclid Av"],
  ["A54","Shepherd Av","Bk","C","Manhattan","Euclid Av"],
  ["A55","Euclid Av","Bk","A C","Manhattan","Queens"],
  ["A57","Grant Av","Bk","A","Manhattan","Queens"],
  ["A59","80 St","Q","A","Manhattan","Far Rockaway/Ozone Park"],
  ["A60","88 St","Q","A","Manhattan","Far Rockaway/Ozone Park"],
  ["A61","Rockaway Blvd","Q","A","Manhattan","Far Rockaway/Ozone Park"],
  ["A63","104 St","Q","A","Manhattan","Ozone Park"],
  ["A64","111 St","Q","A","Manhattan","Ozone Park"],
  ["A65","Ozone Park-Lefferts Blvd","Q","A","Manhattan","Last Stop"],
  ["B04","21 St-Queensbridge","Q","M","Forest Hills-71 Av","Manhattan"],
  ["B06","Roosevelt Island","M","M","Queens","Downtown"],
  ["B08","Lexington Av/63 St","M","M Q","Uptown & Queens","Downtown"],
  ["B10","57 St","M","M","Uptown","Downtown"],
  ["B12","9 Av","Bk","D","Manhattan","Southbound"],
  ["B13","Fort Hamilton Pkwy","Bk","D","Manhattan","Southbound"],
  ["B14","50 St","Bk","D","Manhattan","Southbound"],
  ["B15","55 St","Bk","D","Manhattan","Southbound"],
  ["B16","62 St","Bk","D","Manhattan","Southbound"],
  ["B17","71 St","Bk","D","Manhattan","Southbound"],
  ["B18","79 St","Bk","D","Manhattan","Southbound"],
  ["B19","18 Av","Bk","D","Manhattan","Southbound"],
  ["B20","20 Av","Bk","D","Manhattan","Southbound"],
  ["B21","Bay Pkwy","Bk","D","Manhattan","Southbound"],
  ["B22","25 Av","Bk","D","Manhattan","Coney Island"],
  ["B23","Bay 50 St","Bk","D","Manhattan","Coney Island"],
  ["D01","Norwood-205 St","Bx","D","Last Stop","Manhattan"],
  ["D03","Bedford Park Blvd","Bx","B D","Northbound","Manhattan"],
  ["D04","Kingsbridge Rd","Bx","B D","Northbound","Manhattan"],
  ["D05","Fordham Rd","Bx","B D","Northbound","Manhattan"],
  ["D06","182-183 Sts","Bx","B D","Northbound","Manhattan"],
  ["D07","Tremont Av","Bx","B D","Northbound","Manhattan"],
  ["D08","174-175 Sts","Bx","B D","Northbound","Manhattan"],
  ["D09","170 St","Bx","B D","Northbound","Manhattan"],
  ["D10","167 St","Bx","B D","Northbound","Manhattan"],
  ["D11","161 St-Yankee Stadium","Bx","B D","Northbound","Manhattan"],
  ["D12","155 St","M","B D","The Bronx","Downtown"],
  ["D13","145 St","M","B D","Uptown","Downtown"],
  ["D14","7 Av","M","E B D","Jamaica Center/Bedford Park Blvd/Norwood-205 St","Downtown"],
  ["D15","47-50 Sts-Rockefeller Ctr","M","B D F M","Uptown","Downtown"],
  ["D16","42 St-Bryant Pk","M","B D F M","Uptown","Downtown"],
  ["D17","34 St-Herald Sq","M","B D F M","Uptown","Downtown"],
  ["D18","23 St","M","F M","Uptown","Downtown"],
  ["D19","14 St","M","F M","Uptown","Downtown"],
  ["D20","W 4 St-Wash Sq","M","B D F M","Uptown","Downtown"],
  ["D21","Broadway-Lafayette St","M","B D F M","Uptown","Downtown"],
  ["D22","Grand St","M","B D","Uptown","Brooklyn"],
  ["D24","Atlantic Av-Barclays Ctr","Bk","B Q","Manhattan","Southbound"],
  ["D25","7 Av","Bk","B Q","Manhattan","Southbound"],
  ["D26","Prospect Park","Bk","B Q S","Northbound","Southbound"],
  ["D27","Parkside Av","Bk","Q","Manhattan","Southbound"],
  ["D28","Church Av","Bk","B Q","Manhattan","Southbound"],
  ["D29","Beverley Rd","Bk","Q","Manhattan","Southbound"],
  ["D30","Cortelyou Rd","Bk","Q","Manhattan","Southbound"],
  ["D31","Newkirk Plaza","Bk","B Q","Manhattan","Southbound"],
  ["D32","Avenue H","Bk","Q","Manhattan","Southbound"],
  ["D33","Avenue J","Bk","Q","Manhattan","Southbound"],
  ["D34","Avenue M","Bk","Q","Manhattan","Southbound"],
  ["D35","Kings Hwy","Bk","B Q","Manhattan","Southbound"],
  ["D37","Avenue U","Bk","Q","Manhattan","Southbound"],
  ["D38","Neck Rd","Bk","Q","Manhattan","Southbound"],
  ["D39","Sheepshead Bay","Bk","B Q","Manhattan","Southbound"],
  ["D40","Brighton Beach","Bk","B Q","Manhattan","Southbound"],
  ["D41","Ocean Pkwy","Bk","Q","Manhattan","Coney Island"],
  ["D42","W 8 St-NY Aquarium","Bk","F Q","Manhattan","Coney Island"],
  ["D43","Coney Island-Stillwell Av","Bk","D F N Q","Manhattan","Last Stop"],
  ["E01","World Trade Center","M","E","Uptown","Last Stop"],
  ["F01","Jamaica-179 St","Q","F","Last Stop","Manhattan"],
  ["F02","169 St","Q","F","Jamaica","Manhattan"],
  ["F03","Parsons Blvd","Q","F","Jamaica","Manhattan"],
  ["F04","Sutphin Blvd","Q","F","Jamaica","Manhattan"],
  ["F05","Briarwood","Q","E F","Jamaica","Manhattan"],
  ["F06","Kew Gardens-Union Tpke","Q","E F","Jamaica","Manhattan"],
  ["F07","75 Av","Q","E F","Jamaica","Manhattan"],
  ["F09","Court Sq-23 St","Q","E F","Jamaica Center/Jamaica-179 St","Manhattan"],
  ["F11","Lexington Av/53 St","M","E F","Queens","Downtown"],
  ["F12","5 Av/53 St","M","E F","Queens","Downtown"],
  ["F14","2 Av","M","F","Uptown","Downtown"],
  ["F15","Delancey St-Essex St","M","F","Uptown","Brooklyn"],
  ["F16","East Broadway","M","F","Uptown","Brooklyn"],
  ["F18","York St","Bk","F","Manhattan","Southbound"],
  ["F20","Bergen St","Bk","F G","Northbound","Southbound"],
  ["F21","Carroll St","Bk","F G","Northbound","Southbound"],
  ["F22","Smith-9 Sts","Bk","F G","Northbound","Southbound"],
  ["F23","4 Av-9 St","Bk","F G","Northbound","Southbound"],
  ["F24","7 Av","Bk","F G","Northbound","Southbound"],
  ["F25","15 St-Prospect Park","Bk","F G","Northbound","Southbound"],
  ["F26","Fort Hamilton Pkwy","Bk","F G","Northbound","Southbound"],
  ["F27","Church Av","Bk","F G","Northbound","Southbound"],
  ["F29","Ditmas Av","Bk","F","Manhattan","Southbound"],
  ["F30","18 Av","Bk","F","Manhattan","Southbound"],
  ["F31","Avenue I","Bk","F","Manhattan","Southbound"],
  ["F32","Bay Pkwy","Bk","F","Manhattan","Southbound"],
  ["F33","Avenue N","Bk","F","Manhattan","Southbound"],
  ["F34","Avenue P","Bk","F","Manhattan","Southbound"],
  ["F35","Kings Hwy","Bk","F","Manhattan","Southbound"],
  ["F36","Avenue U","Bk","F","Manhattan","Coney Island"],
  ["F38","Avenue X","Bk","F","Manhattan","Coney Island"],
  ["F39","Neptune Av","Bk","F","Manhattan","Coney Island"],
  ["G05","Jamaica Center-Parsons/Archer","Q","E J Z","Last Stop","Manhattan"],
  ["G06","Sutphin Blvd-Archer Av-JFK Airport","Q","E J Z","Jamaica","Manhattan"],
  ["G07","Jamaica-Van Wyck","Q","E","Jamaica","Manhattan"],
  ["G08","Forest Hills-71 Av","Q","E F M R","Jamaica Center/Jamaica-179 St","Manhattan"],
  ["G09","67 Av","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G10","63 Dr-Rego Park","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G11","Woodhaven Blvd","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G12","Grand Av-Newtown","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G13","Elmhurst Av","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G14","Jackson Hts-Roosevelt Av","Q","E F M R","Jamaica Center/Jamaica-179 St/Forest Hills-71 Av","Manhattan"],
  ["G15","65 St","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G16","Northern Blvd","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G18","46 St","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G19","Steinway St","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G20","36 St","Q","M R","Forest Hills-71 Av","Manhattan"],
  ["G21","Queens Plaza","Q","E F R","Jamaica Center/Jamaica-179 St/Forest Hills-71 Av","Manhattan"],
  ["G22","Court Sq","Q","G","Last Stop","Brooklyn"],
  ["G24","21 St","Q","G","Court Square","Brooklyn"],
  ["G26","Greenpoint Av","Bk","G","Queens","Southbound"],
  ["G28","Nassau Av","Bk","G","Queens","Southbound"],
  ["G29","Metropolitan Av","Bk","G","Queens","Southbound"],
  ["G30","Broadway","Bk","G","Queens","Southbound"],
  ["G31","Flushing Av","Bk","G","Queens","Southbound"],
  ["G32","Myrtle-Willoughby Avs","Bk","G","Queens","Southbound"],
  ["G33","Bedford-Nostrand Avs","Bk","G","Queens","Southbound"],
  ["G34","Classon Av","Bk","G","Queens","Southbound"],
  ["G35","Clinton-Washington Avs","Bk","G","Queens","Southbound"],
  ["G36","Fulton St","Bk","G","Queens","Southbound"],
  ["H01","Aqueduct Racetrack","Q","A","Manhattan","Rockaways"],
  ["H02","Aqueduct-N Conduit Av","Q","A","Manhattan","Rockaways"],
  ["H03","Howard Beach-JFK Airport","Q","A","Manhattan","Rockaways"],
  ["H04","Broad Channel","Q","A S","Inwood-207 St","Rockaways"],
  ["H06","Beach 67 St","Q","A","Manhattan","Far Rockaway"],
  ["H07","Beach 60 St","Q","A","Manhattan","Far Rockaway"],
  ["H08","Beach 44 St","Q","A","Manhattan","Far Rockaway"],
  ["H09","Beach 36 St","Q","A","Manhattan","Far Rockaway"],
  ["H10","Beach 25 St","Q","A","Manhattan","Far Rockaway"],
  ["H11","Far Rockaway-Mott Av","Q","A","Manhattan","Last Stop"],
  ["H12","Beach 90 St","Q","A S","Inwood-207 St/Broad Channel","Rockaway Park"],
  ["H13","Beach 98 St","Q","A S","Inwood-207 St/Broad Channel","Rockaway Park"],
  ["H14","Beach 105 St","Q","A S","Inwood-207 St/Broad Channel","Rockaway Park"],
  ["H15","Rockaway Park-Beach 116 St","Q","A S","Inwood-207 St/Broad Channel","Last Stop"],
  ["J12","121 St","Q","J Z","Jamaica","Manhattan"],
  ["J13","111 St","Q","J","Jamaica","Manhattan"],
  ["J14","104 St","Q","J Z","Jamaica","Manhattan"],
  ["J15","Woodhaven Blvd","Q","J Z","Jamaica","Manhattan"],
  ["J16","85 St-Forest Pkwy","Q","J","Jamaica","Manhattan"],
  ["J17","75 St-Elderts Ln","Q","J Z","Jamaica","Manhattan"],
  ["J19","Cypress Hills","Bk","J","Queens","Manhattan"],
  ["J20","Crescent St","Bk","J Z","Jamaica Center","Manhattan"],
  ["J21","Norwood Av","Bk","J Z","Jamaica Center","Manhattan"],
  ["J22","Cleveland St","Bk","J","Jamaica Center","Manhattan"],
  ["J23","Van Siclen Av","Bk","J Z","Jamaica Center","Manhattan"],
  ["J24","Alabama Av","Bk","J Z","Jamaica Center","Manhattan"],
  ["J27","Broadway Junction","Bk","J Z","Jamaica Center","Manhattan"],
  ["J28","Chauncey St","Bk","J Z","Jamaica Center","Manhattan"],
  ["J29","Halsey St","Bk","J","Jamaica Center","Manhattan"],
  ["J30","Gates Av","Bk","J Z","Jamaica Center","Manhattan"],
  ["J31","Kosciuszko St","Bk","J","Jamaica Center","Manhattan"],
  ["L01","8 Av","M","L","Last Stop","Brooklyn"],
  ["L02","6 Av","M","L","West Side","Brooklyn"],
  ["L03","14 St-Union Sq","M","L","West Side","Brooklyn"],
  ["L05","3 Av","M","L","West Side","Brooklyn"],
  ["L06","1 Av","M","L","West Side","Brooklyn"],
  ["L08","Bedford Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L10","Lorimer St","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L11","Graham Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L12","Grand St","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L13","Montrose Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L14","Morgan Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L15","Jefferson St","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L16","DeKalb Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L17","Myrtle-Wyckoff Avs","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L19","Halsey St","Q","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L20","Wilson Av","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L21","Bushwick Av-Aberdeen St","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L22","Broadway Junction","Bk","L","Manhattan","Canarsie-Rockaway Pkwy"],
  ["L24","Atlantic Av","Bk","L","Manhattan","Canarsie"],
  ["L25","Sutter Av","Bk","L","Manhattan","Canarsie"],
  ["L26","Livonia Av","Bk","L","Manhattan","Canarsie"],
  ["L27","New Lots Av","Bk","L","Manhattan","Canarsie"],
  ["L28","East 105 St","Bk","L","Manhattan","Canarsie"],
  ["L29","Canarsie-Rockaway Pkwy","Bk","L","Manhattan","Last Stop"],
  ["M01","Middle Village-Metropolitan Av","Q","M","Forest Hills-71 Av","Last Stop"],
  ["M04","Fresh Pond Rd","Q","M","Forest Hills-71 Av","Middle Village"],
  ["M05","Forest Av","Q","M","Forest Hills-71 Av","Middle Village"],
  ["M06","Seneca Av","Q","M","Forest Hills-71 Av","Middle Village"],
  ["M08","Myrtle-Wyckoff Avs","Bk","M","Forest Hills-71 Av","Middle Village"],
  ["M09","Knickerbocker Av","Bk","M","Forest Hills-71 Av","Middle Village"],
  ["M10","Central Av","Bk","M","Forest Hills-71 Av","Middle Village"],
  ["M11","Myrtle Av","Bk","M J Z","Forest Hills-71 Av/Jamaica Center","Manhattan"],
  ["M12","Flushing Av","Bk","M J","Forest Hills-71 Av/Jamaica Center","Manhattan"],
  ["M13","Lorimer St","Bk","M J","Forest Hills-71 Av/Jamaica Center","Manhattan"],
  ["M14","Hewes St","Bk","M J","Forest Hills-71 Av/Jamaica Center","Manhattan"],
  ["M16","Marcy Av","Bk","M J Z","Forest Hills-71 Av/Jamaica Center","Manhattan"],
  ["M18","Delancey St-Essex St","M","M J Z","Brooklyn","Middle Village/Broad St"],
  ["M19","Bowery","M","J Z","Brooklyn","Downtown"],
  ["M20","Canal St","M","J Z","Brooklyn","Downtown"],
  ["M21","Chambers St","M","J Z","Brooklyn","Downtown"],
  ["M22","Fulton St","M","J Z","Brooklyn","Downtown"],
  ["M23","Broad St","M","J Z","Brooklyn","Last Stop"],
  ["N02","8 Av","Bk","N","Manhattan","Coney Island"],
  ["N03","Fort Hamilton Pkwy","Bk","N","Manhattan","Coney Island"],
  ["N04","New Utrecht Av","Bk","N","Manhattan","Coney Island"],
  ["N05","18 Av","Bk","N","Manhattan","Coney Island"],
  ["N06","20 Av","Bk","N","Manhattan","Coney Island"],
  ["N07","Bay Pkwy","Bk","N","Manhattan","Coney Island"],
  ["N08","Kings Hwy","Bk","N","Manhattan","Coney Island"],
  ["N09","Avenue U","Bk","N","Manhattan","Coney Island"],
  ["N10","86 St","Bk","N","Manhattan","Coney Island"],
  ["Q01","Canal St","M","N Q","Uptown","Downtown"],
  ["Q03","72 St","M","Q","Uptown","Downtown"],
  ["Q04","86 St","M","Q","Uptown","Downtown"],
  ["Q05","96 St","M","Q","Last Stop","Downtown"],
  ["R01","Astoria-Ditmars Blvd","Q","N W","Last Stop","Manhattan"],
  ["R03","Astoria Blvd","Q","N W","Astoria","Manhattan"],
  ["R04","30 Av","Q","N W","Astoria","Manhattan"],
  ["R05","Broadway","Q","N W","Astoria","Manhattan"],
  ["R06","36 Av","Q","N W","Astoria","Manhattan"],
  ["R08","39 Av-Dutch Kills","Q","N W","Astoria","Manhattan"],
  ["R09","Queensboro Plaza","Q","N W","Astoria","Manhattan"],
  ["R11","Lexington Av/59 St","M","N R W","Queens","Downtown"],
  ["R13","5 Av/59 St","M","N R W","Queens","Downtown"],
  ["R14","57 St-7 Av","M","N Q R W","Uptown","Downtown"],
  ["R15","49 St","M","N R W","Uptown","Downtown"],
  ["R16","Times Sq-42 St","M","N Q R W","Uptown","Downtown"],
  ["R17","34 St-Herald Sq","M","N Q R W","Uptown","Downtown"],
  ["R18","28 St","M","R W","Uptown","Downtown"],
  ["R19","23 St","M","R W","Uptown","Downtown"],
  ["R20","14 St-Union Sq","M","N Q R W","Uptown","Downtown"],
  ["R21","8 St-NYU","M","R W","Uptown","Downtown"],
  ["R22","Prince St","M","R W","Uptown","Downtown"],
  ["R23","Canal St","M","R W","Uptown","Downtown"],
  ["R24","City Hall","M","R W","Uptown","Downtown"],
  ["R25","Cortlandt St","M","R W","Uptown","Downtown"],
  ["R26","Rector St","M","R W","Uptown","Downtown"],
  ["R27","Whitehall St-South Ferry","M","R W","Uptown","Downtown"],
  ["R28","Court St","Bk","R","Manhattan","Southbound"],
  ["R29","Jay St-MetroTech","Bk","R","Manhattan","Southbound"],
  ["R30","DeKalb Av","Bk","B Q R","Manhattan","Southbound"],
  ["R31","Atlantic Av-Barclays Ctr","Bk","D N R","Manhattan","Southbound"],
  ["R32","Union St","Bk","R","Manhattan","Southbound"],
  ["R33","4 Av-9 St","Bk","R","Manhattan","Southbound"],
  ["R34","Prospect Av","Bk","R","Manhattan","Southbound"],
  ["R35","25 St","Bk","R","Manhattan","Southbound"],
  ["R36","36 St","Bk","D N R","Manhattan","Southbound"],
  ["R39","45 St","Bk","R","Manhattan","Southbound"],
  ["R40","53 St","Bk","R","Manhattan","Southbound"],
  ["R41","59 St","Bk","N R","Manhattan","Southbound"],
  ["R42","Bay Ridge Av","Bk","R","Manhattan","Bay Ridge"],
  ["R43","77 St","Bk","R","Manhattan","Bay Ridge"],
  ["R44","86 St","Bk","R","Manhattan","Bay Ridge"],
  ["R45","Bay Ridge-95 St","Bk","R","Manhattan","Last Stop"],
  ["S01","Franklin Av","Bk","S","Last Stop","Prospect Park"],
  ["S03","Park Pl","Bk","S","Franklin Av","Prospect Park"],
  ["S04","Botanic Garden","Bk","S","Franklin Av","Prospect Park"],
  ["S09","Tottenville","SI","SIR","Ferry","Last Stop"],
  ["S11","Arthur Kill","SI","SIR","Ferry","Tottenville"],
  ["S13","Richmond Valley","SI","SIR","Ferry","Tottenville"],
  ["S14","Pleasant Plains","SI","SIR","Ferry","South Shore"],
  ["S15","Prince's Bay","SI","SIR","Ferry","South Shore"],
  ["S16","Huguenot","SI","SIR","Ferry","South Shore"],
  ["S17","Annadale","SI","SIR","Ferry","South Shore"],
  ["S18","Eltingville","SI","SIR","Ferry","South Shore"],
  ["S19","Great Kills","SI","SIR","Ferry","South Shore"],
  ["S20","Bay Terrace","SI","SIR","Ferry","South Shore"],
  ["S21","Oakwood Heights","SI","SIR","Ferry","South Shore"],
  ["S22","New Dorp","SI","SIR","Ferry","South Shore"],
  ["S23","Grant City","SI","SIR","Ferry","South Shore"],
  ["S24","Jefferson Av","SI","SIR","Ferry","South Shore"],
  ["S25","Dongan Hills","SI","SIR","Ferry","South Shore"],
  ["S26","Old Town","SI","SIR","Ferry","South Shore"],
  ["S27","Grasmere","SI","SIR","Ferry","South Shore"],
  ["S28","Clifton","SI","SIR","Ferry","South Shore"],
  ["S29","Stapleton","SI","SIR","Ferry","South Shore"],
  ["S30","Tompkinsville","SI","SIR","Ferry","South Shore"],
  ["S31","St George","SI","SIR","Last Stop","South Shore"],
];
